name: very_good_coffee
description: Flutter application using Very Good CLI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  shimmer: ^3.0.0
  sqflite: ^2.4.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
